import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'
import { FaFacebookF, FaInstagram, FaLinkedinIn, FaTwitter } from 'react-icons/fa'
import {AiFillHeart, AiOutlineDown ,AiFillStar,AiOutlineStar} from 'react-icons/ai'

const Product = () => {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <section className="text-gray-600 body-font overflow-hidden">
  <div className="container px-5 py-24 mx-auto">
    <div className="lg:w-4/5 mx-auto flex flex-wrap">

              <img alt="ecommerce" className="lg:w-1/2 w-full  h-[450px] object-cover object-center rounded border-solid border-2 border-gray-100" src="/tshirt.jpg" />


      <div className="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <h2 className="text-sm title-font text-gray-500 tracking-widest">BRAND NAME</h2>
        <h1 className="text-gray-900 text-3xl title-font font-medium mb-1">The Catcher in the Rye</h1>
        <div className="flex mb-4">
          <span className="flex items-center">
            <AiFillStar size={19} className="text-yellow-400"/>
            <AiFillStar size={19} className="text-yellow-400"/>
            <AiFillStar size={19} className="text-yellow-400"/>
            <AiFillStar size={19} className="text-yellow-400"/>
           <AiOutlineStar size={19}/>
            <span className="text-gray-600 ml-3">4 Reviews</span>
          </span>
          <span className="flex ml-3 pl-3 py-2 border-l-2 border-gray-200 space-x-2s">
          <Link href={"/"} name="linkedin" className="text-gray-500">
          
          <FaFacebookF aria-label='facebook'/>
        </Link>
        <Link href={"/"} className="ml-3 text-gray-500">
            <FaTwitter aria-label='twitter'/>
          
        </Link>
        <Link href={"/"} className="ml-3 text-gray-500">
            <FaInstagram  aria-label='instagram'/>

        </Link>
        <Link href={"/"} className="ml-3 text-gray-500">
            <FaLinkedinIn aria-label='linkedin'/>
        
        </Link>
          </span>
        </div>
        <p className="leading-relaxed">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam indxgo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean shorts keytar banjo tattooed umami cardigan.</p>
        <div className="flex mt-6 items-center pb-5 border-b-2 border-gray-100 mb-5">
          <div className="flex">
            <span className="mr-3">Color</span>
            <button className="border-2 border-gray-300 rounded-full w-6 h-6 focus:outline-none text-transparent" area-label='color-1'>1</button>
            <button className="border-2 border-gray-300 ml-1 bg-gray-700 rounded-full w-6 h-6 focus:outline-none text-transparent" area-label='color-2'>2</button>
            <button className="border-2 border-gray-300 ml-1 bg-indigo-500 rounded-full w-6 h-6 focus:outline-none text-transparent" area-label='color-3'>3</button>
          </div>
          <div className="flex ml-6 items-center">
            <span className="mr-3">Size</span>
            <div className="relative">
              <select className="rounded border appearance-none border-gray-300 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500 text-base pl-3 pr-10">
                <option>SM</option>
                <option>M</option>
                <option>L</option>
                <option>XL</option>
              </select>
              <span className="absolute right-0 top-0 h-full w-10 text-center text-gray-600 pointer-events-none flex items-center justify-center">
                <AiOutlineDown />
              </span>
            </div>
          </div>
        </div>
        <div className="flex">
          <span className="title-font font-medium text-2xl text-gray-900">₹499.00</span>
          <button className="flex ml-auto text-white bg-black border-0 py-2 px-6 focus:outline-none hover:bg-black rounded">Add to Cart</button>
          <button className="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <AiFillHeart size={20} /> <span className='text-transparent'>1</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</section>
    </>
  )
}

export default Product