import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'

const Hoodies = () => {
  return (
<>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <section className="text-gray-600 body-font">
  <div className="container px-5 py-24 mx-auto">
    <div className="flex flex-wrap -m-4">
      <div className="lg:w-1/5 md:w-1/2 p-4 w-full ">
       <div className='border-solid border-2 rounded-t-md'>
       <Link href={'product/tshirt'} className="block relative rounded-t overflow-hidden">
          <div style={{ width: "100%", height: "35vh", position: "relative" }}>
          <Image  loading="lazy" layout="fill"
            objectFit="contain" alt="ecommerce" className=" h-[35vh] block m-auto" src="/hoodies.jpg" />
        </div></Link>
        <div className="m-4 text-center">
          <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">T-Shirts</h3>
          <h2 className="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
          <p className="mt-1">₹499.00</p>
          <p className="mt-1">S, M, L, XL, XXL</p>
        </div>
       </div>
      </div>
      <div className="lg:w-1/5 md:w-1/2 p-4 w-full ">
       <div className='border-solid border-2 rounded-t-md'>
       <Link href={'product/tshirt'} className="block relative rounded-t overflow-hidden">
          <div style={{ width: "100%", height: "35vh", position: "relative" }}>
          <Image  loading="lazy" layout="fill"
            objectFit="contain" alt="ecommerce" className=" h-[35vh] block m-auto" src="/hoodies.jpg" />
        </div></Link>
        <div className="m-4 text-center">
          <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">T-Shirts</h3>
          <h2 className="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
          <p className="mt-1">₹499.00</p>
          <p className="mt-1">S, M, L, XL, XXL</p>
        </div>
       </div>
      </div>
      <div className="lg:w-1/5 md:w-1/2 p-4 w-full ">
       <div className='border-solid border-2 rounded-t-md'>
       <Link href={'product/tshirt'} className="block relative rounded-t overflow-hidden">
          <div style={{ width: "100%", height: "35vh", position: "relative" }}>
          <Image  loading="lazy" layout="fill"
            objectFit="contain" alt="ecommerce" className=" h-[35vh] block m-auto" src="/hoodies.jpg" />
        </div></Link>
        <div className="m-4 text-center">
          <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">T-Shirts</h3>
          <h2 className="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
          <p className="mt-1">₹499.00</p>
          <p className="mt-1">S, M, L, XL, XXL</p>
        </div>
       </div>
      </div>
      <div className="lg:w-1/5 md:w-1/2 p-4 w-full ">
       <div className='border-solid border-2 rounded-t-md'>
       <Link href={'product/tshirt'} className="block relative rounded-t overflow-hidden">
          <div style={{ width: "100%", height: "35vh", position: "relative" }}>
          <Image  loading="lazy" layout="fill"
            objectFit="contain" alt="ecommerce" className=" h-[35vh] block m-auto" src="/hoodies.jpg" />
        </div></Link>
        <div className="m-4 text-center">
          <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">T-Shirts</h3>
          <h2 className="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
          <p className="mt-1">₹499.00</p>
          <p className="mt-1">S, M, L, XL, XXL</p>
        </div>
       </div>
      </div>
      <div className="lg:w-1/5 md:w-1/2 p-4 w-full ">
       <div className='border-solid border-2 rounded-t-md'>
       <Link href={'product/tshirt'} className="block relative rounded-t overflow-hidden">
          <div style={{ width: "100%", height: "35vh", position: "relative" }}>
          <Image  loading="lazy" layout="fill"
            objectFit="contain" alt="ecommerce" className=" h-[35vh] block m-auto" src="/hoodies.jpg" />
        </div></Link>
        <div className="m-4 text-center">
          <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">T-Shirts</h3>
          <h2 className="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
          <p className="mt-1">₹499.00</p>
          <p className="mt-1">S, M, L, XL, XXL</p>
        </div>
       </div>
      </div>
      <div className="lg:w-1/5 md:w-1/2 p-4 w-full ">
       <div className='border-solid border-2 rounded-t-md'>
       <Link href={'product/tshirt'} className="block relative rounded-t overflow-hidden">
          <div style={{ width: "100%", height: "35vh", position: "relative" }}>
          <Image  loading="lazy" layout="fill"
            objectFit="contain" alt="ecommerce" className=" h-[35vh] block m-auto" src="/hoodies.jpg" />
        </div></Link>
        <div className="m-4 text-center">
          <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">T-Shirts</h3>
          <h2 className="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
          <p className="mt-1">₹499.00</p>
          <p className="mt-1">S, M, L, XL, XXL</p>
        </div>
       </div>
      </div>
      <div className="lg:w-1/5 md:w-1/2 p-4 w-full ">
       <div className='border-solid border-2 rounded-t-md'>
       <Link href={'product/tshirt'} className="block relative rounded-t overflow-hidden">
          <div style={{ width: "100%", height: "35vh", position: "relative" }}>
          <Image  loading="lazy" layout="fill"
            objectFit="contain" alt="ecommerce" className=" h-[35vh] block m-auto" src="/hoodies.jpg" />
        </div></Link>
        <div className="m-4 text-center">
          <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">T-Shirts</h3>
          <h2 className="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
          <p className="mt-1">₹499.00</p>
          <p className="mt-1">S, M, L, XL, XXL</p>
        </div>
       </div>
      </div>
      <div className="lg:w-1/5 md:w-1/2 p-4 w-full ">
       <div className='border-solid border-2 rounded-t-md'>
       <Link href={'product/tshirt'} className="block relative rounded-t overflow-hidden">
          <div style={{ width: "100%", height: "35vh", position: "relative" }}>
          <Image  loading="lazy" layout="fill"
            objectFit="contain" alt="ecommerce" className=" h-[35vh] block m-auto" src="/hoodies.jpg" />
        </div></Link>
        <div className="m-4 text-center">
          <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">T-Shirts</h3>
          <h2 className="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
          <p className="mt-1">₹499.00</p>
          <p className="mt-1">S, M, L, XL, XXL</p>
        </div>
       </div>
      </div>
      
     
    </div>
  </div>
</section>
    </>  )
}

export default Hoodies