import axios from 'axios';
import Head from 'next/head'
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react'

const MyOrder = ({ userData}) => {
  const [orders, setOrders] = useState([])
const router = useRouter()

 const getData = async () => {
  await axios
    .get(`${process.env.NEXT_PUBLIC_API_URL}api/order?email=${userData?.email}`)
    .then((res) => {
      console.log("res", res);
      setOrders(res?.data?.data);
    })
    .catch((error) => {
      console.log("error", error);
    });
 }
 useEffect(() => {
  if(userData?.email){
    
    getData()
  }
  }, [userData])
  
  return (
    <>  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
        <div className='container mx-auto text-center my-8 font-semibold text-lg'>
            <div>My Orders</div>
        <main class="flex flex-col">
  <div class="overflow-x-auto ">
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-left text-sm font-light">
          <thead class="border-b font-medium light:border-neutral-500">
            <tr>
              <th scope="col" class="px-6 py-4">#</th>
              <th scope="col" class="px-6 py-4">Email</th>
              <th scope="col" class="px-6 py-4">Amount</th>
              <th scope="col" class="px-6 py-4">Status</th>
              <th scope="col" class="px-6 py-4">Action</th>
            </tr>
          </thead>
          <tbody>
            {orders.map(v => {
              return <tr key={v?._id}
              class="border-b transition duration-300 ease-in-out hover:bg-neutral-100 light:border-neutral-500 light:hover:bg-neutral-600">
              <td class="whitespace-nowrap px-6 py-4 font-medium">{v?.orderId}</td>
              <td class="whitespace-nowrap px-6 py-4">{v?.email}</td>
              <td class="whitespace-nowrap px-6 py-4">₹{v?.amount?.toFixed(2)}</td>
              <td class="whitespace-nowrap px-6 py-4">{v?.status}</td>
              <td class="whitespace-nowrap px-6 py-4 cursor-pointer" onClick={() => router.push(`/order?id=${v?.orderId}`)}>Details</td>
            </tr>
            })}
           
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>
</div>
    </>
  )
}

export default MyOrder