import orderModel from '@/models/orders'
import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'

const Order = ({order}) => {
  const products= JSON.parse(order.products)
console.log('products', products)
  return (
    <>
      <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">BRAND NAME</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">Order Id : #{order?.orderId}</h1>
        <p class="leading-relaxed mb-5 text-green-600">Your order has been sucessfully placed</p>
        {/* <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
        </div> */}
        
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Name</span>
          <span class="ml-auto text-gray-900">Quantity</span>
          <span class="ml-auto text-gray-900">Total</span>
        </div>
        {Object.keys(products)?.map(v => {
          return <div key={products[v]} class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">{products[v]?.name}</span>
          <span class="ml-auto text-gray-900">{products[v]?.qty}</span>
          <span class="ml-auto text-gray-900">₹{products[v]?.price?.toFixed(2)}</span>
        </div>
        })}
        
       
        <div class="flex flex-col mt-3">
          <span class="title-font font-medium text-2xl text-gray-900">Sub Total : ₹{order?.amount?.toFixed(2)}</span>
          <button class="flex ml-auto text-white bg-black border-0 py-2 px-6 focus:outline-none rounded">Track Order</button>
        
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400" />
    </div>
  </div>
</section>
  </>
  )
}

export async function getServerSideProps(context) {
  // let order = await axios
  //   .get(`${process.env.NEXT_PUBLIC_API_URL}api/order?id=${context?.query?.id}`)
  //   .then((res) => {
  //     console.log("res", res);
  //     return res?.data?.data;
  //   })
  //   .catch((error) => {
  //     console.log("error", error);
  //   });
  let data = await orderModel.findOne({orderId: context.query?.id})
  return { props: { order: JSON.parse(JSON.stringify(data)) } };
}

export default Order